### ISSUE TITLE
Powershell

### ISSUE THREAD

**Issue by Deterio** [gilmoreg/douki#1]
Can you add functionality to update MAL through PowerShell? This way I can easily make a PS script run at startup.

**Comment by gilmoreg** [comment]
Unfortunately Douki is a web application and isn't meant to run locally. You could perhaps rig something up to spawn it in a browser window and autofill the fields, but that would be outside my skill set. If I were to make such a thing I would probably write it in a cross-platform way and not in PowerShell.

By the way, there are desktop applications that have the ability to sync between anime list sites, like [Taiga](https://github.com/erengy/taiga). I haven't used it so I don't know but It might have an autorun feature or something similar that might meed your needs.

**Comment by Deterio** [comment]
I'm not that familiar with coding, but I'll try to spawn the browser window and autofill everything. I'll do some research on that.
