### ISSUE TITLE
Douki thinks "some" anime are manga

### ISSUE THREAD

**Issue by Deterio** [gilmoreg/douki#2]
[Image](https://i.imgur.com/bpa37hJ.png)

**Comment by gilmoreg** [comment]
Thanks for reporting. I'll look into it.

**Comment by gilmoreg** [comment]
This might be a bug on Anilist's end. I'm working with them to troubleshoot.

**Comment by gilmoreg** [comment]
Fixed on Anlist's end. Thanks again for bringing this up.
