### ISSUE TITLE
Same anime keep getting re-synced

### ISSUE THREAD

**Issue by Deterio** [gilmoreg/douki#3]
The same anime always keep getting re-synced, despite being in update mode.

![Screenshot](https://user-images.githubusercontent.com/22274951/38498969-730cd2b8-3c06-11e8-8753-fbc49607d4b0.png)

**Comment by gilmoreg** [comment]
This happens when Anilist and MAL disagree about how many episodes or chapters something has. I might be able to implement some logic to check this, but I'm not sure how soon I can get to it.

**Comment by Deterio** [comment]
Alright, thanks for the reply!

**Comment by gilmoreg** [comment]
Making a PR to address this issue. I'll post on the thread to get feedback.
