### ISSUE TITLE
HTTPS SSL Errors

### ISSUE THREAD

**Issue by beeequeue** [gilmoreg/douki#8]
Your SSL certificate is incorrectly configured and sends certificates for random scummy websites instead.

e.g.
`www.3commas.org`
`impression.adinmo.com`
`sixteenwomen.com`
![image](https://user-images.githubusercontent.com/472500/44056484-afabcb34-9f48-11e8-8c88-b26d63960a8a.png)

**Comment by gilmoreg** [comment]
Thanks for letting me know. I suspended the paid dyno on Heroku while the site is nonfunctional; I do not know why this is their default behavior in this case. For now I've simply erased the DNS record so that it points nowhere.
